### ISSUE TITLE
[Bug]: Unwanted Reload of Hashtag Search Results Page

### ISSUE THREAD

**Issue by Beleggrodion** [pixelfed/pixelfed-rn#382]
### Description

The hashtag search took some times very long (also on the web so i think it's because of the ressource limit of my instance) . So if had results and switch out of the app or i receive the lock screen of my phone, the app triggers a re-search of the already found results. This is realy anoying and in my oppinion a bug. 

I think a full re-search shoul'd only be applied when i scroll up. I mean scroll down also triggers the search to add the next results of my hashtag search. Because when this re-search is triggered it starts completly from the beginning. so i need to scroll down again until i reach the part of my search which i don't looked into. 

### Steps to reproduce

1. Search a Hashtag
2. See Results and Scroll Down
3. Wait for Lock Screen of Phone or Switch shortly to another App (ex. Email)
4. Switch Back

### Pixelfed version

1.4.0.1

### Platforms

Android

### Device model

Samsung Galaxy S20 FE 5G (Android 13)

### Acknowledgements

Yes

**Comment by dansup** [comment]
Fixed in 67d137f

**Comment by Beleggrodion** [comment]
Sorry. need to open this again ;-) 

I updated to the newest pixelfed version 1.7.0.1 from playstore today, and have still issues.  When i switch to another app or lock screen appears, a reload screen is initiated after i switch back.  The only difference is now, that all already displayed results re-appear after "reload" screen, which is a little bit better than before but still not a pleasant user experience. :/
